language: php

php:
  - 5.4

before_script:
  - export TEST_BASE_URL=http//localhost/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - curl -O -s http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar selenium-server-standalone-2.25.0.jar &
  - cd ..
  - mkdir testSijit
  - cd testSijit
  - cp ../sijit/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - rm -rf vendor/dojo/Sds
  - cp -r ../sijit vendor/dojo
  - mv vendor/dojo/sijit vendor/dojo/Sds
  - npm install connect
  - sudo node vendor/dojo/Sds/.travis/server.js &
  - sleep 3

script:
  - cd vendor/dojo/Sds
  - phpunit
