language: php

php:
  - 5.4

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start #start headless frame buffer
  - cd ..
  - mkdir testSijit #begin composer install
  - cd sijit
  - cp ../sijit/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php  
  - php composer.phar install
  - rm -rf vendor/dojo/Sds
  - cp -r ../sijit vendor/dojo
  - mv vendor/dojo/sijit vendor/dojo/Sds #complete composer install
  - npm install connect
  - sudo node vendor/dojo/Sds/.travis/server.js & #start webserver
  
script:
  - cd vendor/dojo/Sds
  - phpunit
